.TH B2SUM 1 blakesum
.SH NAME
b2sum - Compute and check BLAKE2 message digests
.SH SYNOPSIS
.B bsum
[-l bits | -X bits] [-c | -B | -L | -U] [-sxz]
.RI [ file "] ..."
.SH DESCRIPTION
Print or check BLAKE2 checksums, using BLAKE2b by default.
.SH OPTIONS
The
.B b2sum
utility conforms to the Base Definitions volume of POSIX.1-2017,
.IR "Section 12.2" ,
.IR "Utility Syntax Guidelines" .
.PP
The following options are supported:
.TP
.B -B
Output checksums in binary representation. This suppresses
the filenames and checksum delimiters. Only the checksums
are printed.
.TP
.B -c
Read BLAKE2 sums from the file and check them against the
files on your systems. The input files files should be
formatted as the output of this program, or similarly.
This is not going to work if any of the filenames in the
input files starts with <space> or <tab>, or if they
contain a <newline, unless the
.B -z
option is also used.
.TP
.B -L
Output checksums in lower-case hexadecimal representation. (Default)
.TP
.BI "-l " bits
Select output size, valid values are multiples of 8
between 8 and 512, inclusively, or if the
.B -s
option is used between 8 and 256, inclusively.
(Default is maximum.)
.TP
.B -s
Use BLAKE2s instead of BLAKE2b.
.TP
.B -U
Output checksums in upper-case hexadecimal representation.
.TP
.BI "-X " bits
Use BLAKE2Xb instead of BLAKE2b or BLAKE2Xs instead of BLAKE2s,
and select the extended output function output length, int bits,
must be a non-zero multiple of 8, and no greater than
34359738360 or (if the
.B -s
option is used) 524280.
.TP
.B -x
Convert input files from hexadecimal form to binary form
before calculating the checksums.
.TP
.B -z
Lines end with NUL instead of LF. If used with
.BR -c ,
this applies to read files (not the output), but it will
also apply more strict parsing and allow any whitespace
in file names.
.SH OPERANDS
The following operands are supported:
.TP
.I file
File to read. The standard input will be used
.B -
or no
.I file
is specified.
.SH EXIT STATUS
.TP
0
Successful completion.
.TP
1
Checksums did not match or a file did not exist.
.TP
2
An error occurred.
.SJ SEE ALSO
.BR bsum (1)
